### ISSUE TITLE
Mount 'er Good

### ISSUE THREAD

**Issue by Hereticide** [FiftyCaliber/ToS-Addons#3]
I don't know how else, or where else, to suggest this.. but since you have a very solid grasp of companion positioning via Mount 'er Good, would you be so kind as to make a similar addon to immediately recall all summons to your position? 

Necromancer skeleton's and Paladin converts specifically all have a habit of wandering off and attacking another enemy and never returning to where you need them, no matter how far you get from them. The Paladin converts especially so as they are designed to teleport to you but fail to do so if they are engaged with an enemy.

If possible the summoning community would love if you could make a similar addon for us! Reel in our stray summons please! =)

**Comment by FiftyCaliber** [comment]
Honestly, this addon is pushing the limits of what I would consider "legal". The only reason I made it anyway was because the companions issue of getting frozen and doing literally nothing. Its not merely a matter of bad AI and having to run over to your companion in order to mount it, the issue is when its frozen its no where nearby to even mount in the first place. KToS actually just got a patch that functions similarly to my Mount 'er Good addon giving players a slash command to teleport the pet to your location.

So no sorry but I will not be making an addon for that.
